# Generated by Django 3.1.7 on 2021-04-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='', max_length=20, verbose_name='用户名')),
                ('pw', models.CharField(max_length=20, verbose_name='密码')),
                ('nickname', models.CharField(default='', max_length=100, verbose_name='昵称')),
                ('email', models.CharField(default='', max_length=50, verbose_name='电子邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='决策名字')),
                ('n', models.IntegerField(default=0, verbose_name='城市数目')),
                ('m', models.IntegerField(default=0, verbose_name='旅行商数目')),
                ('chrom_num', models.IntegerField(default=0, verbose_name='染色体数目')),
                ('state', models.IntegerField(default=0, verbose_name='状态')),
                ('city', models.CharField(default='', max_length=10000, null=True, verbose_name='城市列表')),
                ('gen', models.IntegerField(default=0, null=True, verbose_name='第几代')),
                ('solution', models.CharField(max_length=2000, null=True, verbose_name='方案')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.user')),
            ],
        ),
    ]
