# Generated by Django 3.1.7 on 2021-04-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_decision_solution_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='solution_displayed',
            field=models.CharField(max_length=2000, null=True, verbose_name='用来显示的格式化决策结果'),
        ),
    ]
