# Generated by Django 3.1.7 on 2021-04-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20210427_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='balance_factor',
            field=models.CharField(default='', max_length=1000, verbose_name='平衡差'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='gen',
            field=models.IntegerField(default=0, verbose_name='第几代'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=models.CharField(default='', max_length=2000, verbose_name='方案'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_displayed',
            field=models.CharField(default='', max_length=2000, verbose_name='用来显示的格式化决策结果'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='total_distance',
            field=models.CharField(default='', max_length=1000, verbose_name='总距离'),
        ),
    ]
