# Generated by Django 3.1.7 on 2021-04-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20210427_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='balance_factor',
            field=models.CharField(max_length=100, null=True, verbose_name='平衡差'),
        ),
        migrations.AddField(
            model_name='decision',
            name='gen',
            field=models.IntegerField(default=0, verbose_name='第几代'),
        ),
        migrations.AddField(
            model_name='decision',
            name='solution',
            field=models.CharField(max_length=2000, null=True, verbose_name='方案'),
        ),
        migrations.AddField(
            model_name='decision',
            name='solution_displayed',
            field=models.CharField(max_length=2000, null=True, verbose_name='用来显示的格式化决策结果'),
        ),
        migrations.AddField(
            model_name='decision',
            name='total_distance',
            field=models.CharField(max_length=100, null=True, verbose_name='总距离'),
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
